dependencies:
  - name: elasticsearch
    version: 7.15.0
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: 7.15.0
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: filebeat
    version: 7.15.0
    repository: https://helm.elastic.co
    condition: filebeat.enabled
  - name: metricbeat
    version: 7.15.0
    repository: https://helm.elastic.co
    condition: metricbeat.enabled
  - name: heartbeat
    version: 7.15.0
    condition: heartbeat.enabled